### PR TITLE
fix: Removing retrying from blocking write

### LINKED ISSUE #235: WriteAPIBlocking.WritePoint does not always return error if influx not reachable
Hi,

I noticed that the WriteAPIBlocking gives inconsistent return values when InfluxDB is not reachable.
When testing out the app behavior when Influx is not running, I noticed that some write attempts yield errors but many run through as if they worked fine (err==nil). 

In my case I'm writing concurrently from 3 separate go routines (about 3 points each per second) calling a function with the code below. According to issues/docs the WriteAPIBlocking should be thread-safe. 

Any ideas what could be the issue?

The code in questions is based on the basic blocking write example

```
	        startTime := time.Now()
		err := influx.writeAPIBlocking.WritePoint(context.Background(), newPoints...)
		if err != nil {
			logger.Errorf("Error saving data to InfluxDB. Reason: %s", err.Error())
			return err
		}
		log.Infof("Saved %d %s point(s) in %d ms", len(newPoints), dataset.MeasurementName, time.Since(startTime).Milliseconds())
		return nil
```

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Turn off influx db (or use wrong url/port)
2. Attempt to write points (from several go routines)
3. err struct is sometimes nil indicating that everything was written OK

__Expected behavior:__
a not reachable influxdb should consistently produce errors on write

__Actual behavior:__
err is sometimes nil

__Specifications:__
 - Client Version: 2.2.2
 - InfluxDB Version: 2.0.4
 - Platform: Ubuntu 18.04 x64

### LINKED ISSUE #236: Retries are attempted even if MaxRetries is set to zero
__Steps to reproduce:__
Given the following client code snippet

```
	options := influxdb2.DefaultOptions().SetMaxRetries(0)
	client := influxdb2.NewClientWithOptions(url, authToken, options)
	defer client.Close()
	writeAPI := client.WriteAPIBlocking("", dbName)
        err := writeAPI.WritePoint(context.Background(), point)
        if err != nil {
            fmt.Printf("Error: %v", err)
        }
```

where `url` is the URL of an InfluxDB instance that is unreachable (i.e. results in a connection error), the `WritePoint()` method may attempt an implicit deferred retry (instead of immediately returning a connection error), even though MaxRetries was set to 0.

__Expected behavior:__
The `WritePoint()` method should always return an error in this case.

__Actual behavior:__
No error is returned.

__Specifications:__
 - Client Version: 2.2.2
 - InfluxDB Version: n/a (testing against an unreachable InfluxDB instance)
 - Platform: MacOS 10.15.7

### PR DESCRIPTION
**Pull request by vlastahajek**
Closes #235

## Proposed Changes

Blocking write client doesn't use retry handling.

## Checklist

- [X] CHANGELOG.md updated
- [X] Rebased/mergeable
- [X] A test has been added if appropriate
- [X] Tests pass
- [X] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: api/http/error.go [hunk 1]
```diff
@@ -30,6 +31,10 @@ func (e *Error) Error() string {
 	}
 }
 
+func (e *Error) ToError() error {
```
Comment (sranka) [inline api/http/error.go:34]:
```suggestion
func (e *Error) Unwrap() error {
```
Unwrap was introduced since go 1.13

File: internal/write/service.go [hunk 2]
```diff
@@ -55,7 +55,15 @@ func NewService(org string, bucket string, httpService http2.Service, options *w
 	if retryBufferLimit == 0 {
 		retryBufferLimit = 1
 	}
-	return &Service{org: org, bucket: bucket, httpService: httpService, writeOptions: options, retryQueue: newQueue(int(retryBufferLimit)), retryExponentialBase: 5}
+	u, _ := url.Parse(httpService.ServerAPIURL())
+	u, _ = u.Parse("write")
+	params := u.Query()
+	params.Set("org", org)
+	params.Set("bucket", bucket)
+	params.Set("precision", precisionToString(options.Precision()))
```
Comment (sranka) [inline internal/write/service.go:63]: this is probably related to a change in the WriteURL func

**Review by sranka — CHANGES_REQUESTED** [review]

File: api/http/error.go (hunk 1 above)
Comment (vlastahajek) [reply api/http/error.go:34]: Unwrap seems to be related to the case when this `Error` struct just wraps another `error`. This function just creates `error` from the string composed from wrapped fields.

File: internal/write/service.go (hunk 2 above)
Comment (vlastahajek) [reply internal/write/service.go:63]: Lazy setting the complete write url was removed as considered useless and complicated as it needed to be synced.

File: api/http/error.go (hunk 1 above)
Comment (sranka) [reply api/http/error.go:34]: `ToError` func on an `Error` struct that itself implements =error= is still confusing to me. I think think that Unwrap would be better.

**Review by sranka — APPROVED** [review]
