### PR TITLE
fix: added mutex around writes to logger struct for concurrent use of many…

### LINKED ISSUE #268: Race condition on logger struct with multiple concurrent clients
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run multiple clients concurrently with race detection.

__Expected behavior:__
No race conditions.

__Actual behavior:__
Race detected on writes to logger struct when setting log level.

__Specifications:__
 - Client Version: v2
 - InfluxDB Version: v2.0.5
 - Platform: ubuntu 20.04

### PR DESCRIPTION
**Pull request by mateuszkowalke**
… clients

Closes #268

## Proposed Changes

added mutex around logger struct

## Checklist

- [ ] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] Tests pass
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: log/logger.go [hunk 1]
```diff
@@ -49,21 +50,27 @@ type Logger interface {
 }
 
 // logger provides default implementation for Logger. It logs using Go log API
+// mutex is needed in cases when multiple clients run concurrently
 type logger struct {
 	prefix   string
 	logLevel uint
+	sync.Mutex
```
Comment (vlastahajek) [inline log/logger.go:57]:
```suggestion
	lock sync.Mutex
```
`Logger` has no functionality related to Mutex, so embedding (inheriting) is not needed.

File: log/logger.go [hunk 2]
```diff
@@ -49,21 +50,27 @@ type Logger interface {
...
 }
 
 func (l *logger) SetLogLevel(logLevel uint) {
+	l.Lock()
```
Comment (vlastahajek) [inline log/logger.go:61]:
```suggestion
	l.lock.Lock()
```

File: log/logger.go [hunk 3]
```diff
@@ -49,21 +50,27 @@ type Logger interface {
...
 	l.logLevel = logLevel
+	l.Unlock()
```
Comment (vlastahajek) [inline log/logger.go:63]:
```suggestion
	l.lock.Unlock()
```

File: log/logger.go [hunk 4]
```diff
@@ -49,21 +50,27 @@ type Logger interface {
...
 }
 
 func (l *logger) LogLevel() uint {
 	return l.logLevel
 }
 
 func (l *logger) SetPrefix(prefix string) {
+	l.Lock()
```
Comment (vlastahajek) [inline log/logger.go:71]:
```suggestion
	l.lock.Lock()
```

File: log/logger.go [hunk 5]
```diff
@@ -49,21 +50,27 @@ type Logger interface {
...
 	l.prefix = prefix
+	l.Unlock()
```
Comment (vlastahajek) [inline log/logger.go:73]:
```suggestion
	l.lock.Unlock()
```

**Review by vlastahajek — CHANGES_REQUESTED** [review]
@mateuszkowalke, thanks for the issue and fix. Just a small change to complete this.

**Review by vlastahajek — APPROVED** [review]
